version: "3"

services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
  php:
    build: .
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports: 
        - 8888:80
    depends_on: 
        - db
